---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
  - password: testpassword
  tasks:
    - name: "Include ansible-raspberry-provisioning"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
