---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: raspi
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
